<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="index.html" />
        <Content Include="styles.css" />
        <TypeScriptCompile Include="vite.config.ts" />
        <None Include="package.json" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Joypad.fs" />
        <Compile Include="JsBindings.fs" />
        <Compile Include="Audio.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Fable.Browser.Dom" Version="2.20.0" />
        <PackageReference Include="Fable.Browser.Url" Version="1.4.0" />
        <PackageReference Include="Fable.Core" Version="5.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FameBoy\FameBoy.fsproj" />
    </ItemGroup>


</Project>
