<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Hardware.fs" />
        <Compile Include="Cartridges\Mbc1Cart.fs" />
        <Compile Include="Cartridges\Mbc3Cart.fs" />
        <Compile Include="Cartridges\Mbc5Cart.fs" />
        <Compile Include="Cartridges\Cartridge.fs" />
        <Compile Include="Interrupts.fs" />
        <Compile Include="Joypad.fs" />
        <Compile Include="IoController.fs" />
        <Compile Include="Memory.fs" />
        <Compile Include="Cpu\State.fs" />
        <Compile Include="Cpu\Instructions.fs" />
        <Compile Include="Cpu\Executors\Utils.fs" />
        <Compile Include="Cpu\Executors\Arithmetic.fs" />
        <Compile Include="Cpu\Executors\Bitwise.fs" />
        <Compile Include="Cpu\Executors\Control.fs" />
        <Compile Include="Cpu\Executors\Load.fs" />
        <Compile Include="Cpu\Executors\Logic.fs" />
        <Compile Include="Cpu\Opcodes.fs" />
        <Compile Include="Cpu\Execute.fs" />
        <Compile Include="Ppu.fs" />
        <Compile Include="Startup.fs" />
        <Compile Include="Serial.fs" />
        <Compile Include="Timer.fs" />
        <Compile Include="Emulator.fs" />
    </ItemGroup>

    <PropertyGroup>
        <WarningsAsErrors>FS0025</WarningsAsErrors>
    </PropertyGroup>
</Project>
